apiVersion: v1
description: "Feast Feature Server: Online feature serving service for Feast"
name: feature-server
version: 0.22.5
appVersion: v0.22.5
keywords:
- machine learning
- big data
- mlops
home: https://github.com/feast-dev/feast