apiVersion: v1
description: "Transformation service: to compute on-demand features"
name: transformation-service
version: 0.22.5
appVersion: v0.22.5
keywords:
- machine learning
- big data
- mlops
home: https://github.com/feast-dev/feast